server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ejpa_example?useSSL=false
    username: root
    password: 123456

# 多租户数据源配置
multitenancy:
  dataSourcesProps:
    -
      tenantId: 0
      url: jdbc:mysql://localhost:3306/db_ejpa_example?useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    -
      tenantId: 1
      url: jdbc:mysql://localhost:3306/db_ejpa_example_0?useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    -
      tenantId: 2
      url: jdbc:mysql://localhost:3306/db_ejpa_example_1?useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
